version: "2"
services:
  app:
    image: gzero/node-image:v4.0
    restart: "no"
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - .:/app
      - yarn-cache:/.yarn-cache

  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: karta_kredytowa
      POSTGRES_USER: karta_kredytowa
    ports:
      - 5432:5432

  db-tests:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: karta_kredytowa
      POSTGRES_USER: karta_kredytowa
    ports:
      - 5433:5432

volumes:
  yarn-cache:
    driver: "local"
